module.exports = {
  city: { type: String},
  country: { type: String},
  created_at: { type: Date},
  updated_at: {type: Date},
  firstname: { type: String},
  lastname:{ type: String},
  profile:{ type: String},
  profile_medium:{ type: String},
  reference:{ type: String},
  sex:{ type: String},
  stravaId:{ type: Number},
  username:{ type: String},
  stravaId:{ type: String},
  active:{ type: Boolean},
  height: { type: Number },
  date_of_birth: { type: Date },
  fc_max: { type: Number, default: 200 },
  tss: { type: Number },
  email: { type: String, unique: true, required: true, index: true },
}
